"use client";

import { useEffect, useState } from "react";
import { Icon, ImagePh } from "../ui";

type Media = { id: string; url: string; caption: string | null; alt_text: string | null; role: string; source: string; rights_confirmed: boolean; status: string; width: number | null; height: number | null; rejection_reason: string | null; businesses: { name: string; slug: string } | { name: string; slug: string }[] };
export function AdminMedia({ toast }: { toast: (m: string) => void }) {
  const [view,setView]=useState("quality"), [rows,setRows]=useState<Media[]>([]), [loading,setLoading]=useState(true);
  const load=async()=>{setLoading(true);const r=await fetch(`/api/admin/media?view=${view}`);const d=await r.json().catch(()=>({}));setRows(d?.ok?d.media||[]:[]);setLoading(false);};
  useEffect(()=>{void load();},[view]);
  const act=async(row:Media,action:"approve"|"reject")=>{const reason=action==="reject"?prompt("Reason shown in the audit record:","Low quality, irrelevant, or rights not confirmed")||"Rejected":undefined;const r=await fetch("/api/admin/media",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:row.id,action,reason})});const d=await r.json().catch(()=>({}));if(d?.ok){toast(`Image ${action}d`);await load();}else toast("Couldn't update image.");};
  return <div className="admin-section"><div className="admin-sec-head"><div><h2>Media quality</h2><p>Audit provenance, rights, dimensions and business relevance. Rejection removes an image from its public gallery.</p></div></div><div className="flex g8 wrap" style={{marginBottom:16}}>{["quality","pending","rejected","all"].map(v=><button key={v} className={`btn btn-sm ${view===v?"btn-primary":"btn-soft"}`} onClick={()=>setView(v)}>{v}</button>)}</div>{loading?<div className="card" style={{height:100,opacity:.5}}/>:rows.length===0?<div className="card" style={{padding:30,textAlign:"center"}}><Icon name="camera" size={24}/><h3>Queue is clear</h3></div>:<div className="grid-cards">{rows.map(row=>{const b=Array.isArray(row.businesses)?row.businesses[0]:row.businesses;return <div className="card" key={row.id} style={{overflow:"hidden"}}><ImagePh src={row.url} label={row.alt_text||row.caption||b?.name||"Business image"} ratio="4/3"/><div style={{padding:14}}><h3>{b?.name}</h3><p className="faint">{row.role} · {row.source} · {row.width||"?"}×{row.height||"?"} · rights {row.rights_confirmed?"confirmed":"missing"}</p>{row.rejection_reason&&<p className="coupon-error">{row.rejection_reason}</p>}<div className="flex g8 wrap mt12">{row.status!=="approved"&&<button className="btn btn-primary btn-sm" onClick={()=>act(row,"approve")}>Approve</button>}{row.status!=="rejected"&&<button className="btn btn-soft btn-sm" onClick={()=>act(row,"reject")}>Reject</button>}<a className="btn btn-ghost btn-sm" href={`/business/${b?.slug}`} target="_blank" rel="noopener">Listing</a></div></div></div>;})}</div>}</div>;
}
