/* Humble Halal — Events data (ported from events-data.jsx) */
import type { Category, EventItem, Ticket } from "./types";
import { slugify } from "./slug";

const IMG = (id: string) =>
  "https://images.unsplash.com/photo-" + id + "?auto=format&fit=crop&w=900&q=70";

export const eventCats: Category[] = [
  { id: "bazaar", label: "Bazaars & Markets", icon: "store" },
  { id: "workshop", label: "Classes & Workshops", icon: "sparkles" },
  { id: "talk", label: "Talks & Ta’lim", icon: "mosque" },
  { id: "community", label: "Community & Family", icon: "family" },
  { id: "charity", label: "Charity & Fundraising", icon: "heart" },
  { id: "business", label: "Business & Networking", icon: "building" },
  { id: "youth", label: "Kids & Youth", icon: "users" },
];

// Photo IDs confirmed-loading (food/market/people/class themes)
const EP = {
  bazaar: "1555939594-58d7cb561ad1",
  market: "1504674900247-0877df9cc836",
  lantern: "1533900298318-6b8da08a523e",
  cooking: "1556910103-1c02745aae4d",
  calligraphy: "1597484661643-2f5fef640dd1",
  fashion: "1490481651871-ab68de25d43d",
  talk: "1505373877841-8d25f7d46678",
  lecture: "1524178232363-1fb2b075b655",
  community: "1511795409834-ef04bbd61622",
  family: "1543269865-cbf427effbad",
  charity: "1593113646773-028c64a8f1b8",
  hands: "1488521787991-ed7bbaae773c",
  network: "1556761175-5973dc0f32e7",
  youth: "1503676260728-1c00da094a0b",
  kids: "1587616211892-f743fcca64f9",
  coffee: "1554118811-1e0d58224f24",
};

export const events: EventItem[] = [
  {
    id: "e1",
    title: "Geylang Serai Ramadan Bazaar 2026",
    catId: "bazaar",
    cat: "Bazaars & Markets",
    img: IMG(EP.lantern),
    tone: "gold",
    free: true,
    priceFrom: 0,
    dateLabel: "Sat, 14 Mar",
    timeLabel: "4:00 PM – 11:00 PM",
    dateISO: "2026-03-14",
    multiDay: "Runs daily through Ramadan",
    venue: "Geylang Serai, Wisma Geylang Sim",
    area: "Geylang Serai",
    capacity: 5000,
    taken: 0,
    rsvp: true,
    organiserId: "l7",
    organiser: "Wisma Geylang Sim",
    organiserBiz: true,
    blurb:
      "Singapore’s most-loved Ramadan bazaar returns — 300+ stalls of street food, fashion, and festive treats.",
    tags: ["Halal food", "Family friendly", "Prayer space nearby"],
    prayerNearby: true,
    halalCatering: true,
    featured: true,
    attendees: 1820,
  },
  {
    id: "e2",
    title: "Modern Nasi Padang Masterclass",
    catId: "workshop",
    cat: "Classes & Workshops",
    img: IMG(EP.cooking),
    tone: "gold",
    free: false,
    priceFrom: 48,
    tiers: [
      { name: "Standard", price: 48, perks: "Hands-on class + recipe booklet" },
      { name: "Pair", price: 88, perks: "For two, share a station" },
    ],
    dateLabel: "Sun, 22 Feb",
    timeLabel: "10:00 AM – 1:00 PM",
    dateISO: "2026-02-22",
    venue: "Warung Bumbu Rempah, Tampines",
    area: "Tampines",
    capacity: 18,
    taken: 14,
    rsvp: false,
    organiserId: "l1",
    organiser: "Warung Bumbu Rempah",
    organiserBiz: true,
    blurb:
      "Cook rendang and sambal goreng from scratch with our head chef, then sit down to eat what you made.",
    tags: ["Hands-on", "Ingredients provided", "Halal"],
    prayerNearby: true,
    halalCatering: true,
    featured: true,
    attendees: 14,
  },
  {
    id: "e3",
    title: "Friday Ta’lim: The Prophetic Character",
    catId: "talk",
    cat: "Talks & Ta’lim",
    img: IMG(EP.talk),
    tone: "emerald",
    free: true,
    priceFrom: 0,
    dateLabel: "Fri, 20 Feb",
    timeLabel: "8:15 PM – 9:30 PM",
    dateISO: "2026-02-20",
    venue: "Masjid Sultan, Kampong Glam",
    area: "Bugis",
    capacity: 200,
    taken: 96,
    rsvp: true,
    organiserId: null,
    organiser: "Masjid Sultan",
    organiserBiz: false,
    blurb:
      "A weekly evening reminder on akhlaq and adab. All are welcome; seating after Isyak.",
    tags: ["Free entry", "Brothers & sisters", "Wheelchair access"],
    prayerNearby: true,
    halalCatering: false,
    featured: false,
    attendees: 96,
  },
  {
    id: "e4",
    title: "Modest Fashion Pop-Up & Styling",
    catId: "bazaar",
    cat: "Bazaars & Markets",
    img: IMG(EP.fashion),
    tone: "gold",
    free: true,
    priceFrom: 0,
    dateLabel: "Sat, 28 Feb",
    timeLabel: "12:00 PM – 8:00 PM",
    dateISO: "2026-02-28",
    venue: "The Modest Thread, Bugis Junction",
    area: "Bugis",
    capacity: 300,
    taken: 138,
    rsvp: true,
    organiserId: "l8",
    organiser: "The Modest Thread",
    organiserBiz: true,
    blurb:
      "Meet local modestwear labels, free hijab styling, and member-only launch prices for one weekend.",
    tags: ["Free entry", "Muslim-owned labels", "Refreshments"],
    prayerNearby: false,
    halalCatering: true,
    featured: true,
    attendees: 138,
  },
  {
    id: "e5",
    title: "Iftar for the Community — Charity Dinner",
    catId: "charity",
    cat: "Charity & Fundraising",
    img: IMG(EP.charity),
    tone: "emerald",
    free: false,
    priceFrom: 25,
    tiers: [
      { name: "Seat", price: 25, perks: "One iftar seat" },
      {
        name: "Sponsor a table",
        price: 250,
        perks: "Sponsor 10 seats for those in need",
      },
    ],
    dateLabel: "Sat, 21 Mar",
    timeLabel: "6:30 PM – 9:00 PM",
    dateISO: "2026-03-21",
    venue: "Madinah Spice Kitchen, Bedok",
    area: "Bedok",
    capacity: 120,
    taken: 74,
    rsvp: false,
    organiserId: "l10",
    organiser: "Madinah Spice Kitchen",
    organiserBiz: true,
    blurb:
      "Break fast together and sponsor a seat for a family in need. All proceeds go to local welfare.",
    tags: ["Halal catering", "Prayer space", "Donation"],
    prayerNearby: true,
    halalCatering: true,
    featured: false,
    attendees: 74,
  },
  {
    id: "e6",
    title: "Arabic Calligraphy for Beginners",
    catId: "workshop",
    cat: "Classes & Workshops",
    img: IMG(EP.calligraphy),
    tone: "cream",
    free: false,
    priceFrom: 35,
    tiers: [{ name: "Standard", price: 35, perks: "Materials + take-home piece" }],
    dateLabel: "Sun, 1 Mar",
    timeLabel: "2:00 PM – 4:30 PM",
    dateISO: "2026-03-01",
    venue: "Qahwa & Co., Haji Lane",
    area: "Bugis",
    capacity: 12,
    taken: 12,
    rsvp: false,
    organiserId: "l2",
    organiser: "Qahwa & Co.",
    organiserBiz: true,
    blurb:
      "Learn the basics of the naskh script with a local artist, over specialty coffee and dates.",
    tags: ["All levels", "Materials provided", "Refreshments"],
    prayerNearby: false,
    halalCatering: true,
    featured: false,
    attendees: 12,
    soldOut: true,
  },
  {
    id: "e7",
    title: "Muslim Founders Networking Night",
    catId: "business",
    cat: "Business & Networking",
    img: IMG(EP.network),
    tone: "emerald",
    free: false,
    priceFrom: 15,
    tiers: [
      { name: "Member", price: 15, perks: "Entry + 1 drink" },
      { name: "Non-member", price: 25, perks: "Entry + 1 drink" },
    ],
    dateLabel: "Thu, 26 Feb",
    timeLabel: "7:00 PM – 9:30 PM",
    dateISO: "2026-02-26",
    venue: "Qahwa & Co., Haji Lane",
    area: "Bugis",
    capacity: 60,
    taken: 41,
    rsvp: false,
    organiserId: "l2",
    organiser: "Humble Halal Community",
    organiserBiz: false,
    blurb:
      "Connect with Muslim entrepreneurs and creatives over coffee. Short founder stories, then open mingling.",
    tags: ["Networking", "Halal refreshments"],
    prayerNearby: false,
    halalCatering: true,
    featured: false,
    attendees: 41,
  },
  {
    id: "e8",
    title: "Kids’ Quran & Storytelling Morning",
    catId: "youth",
    cat: "Kids & Youth",
    img: IMG(EP.youth),
    tone: "gold",
    free: true,
    priceFrom: 0,
    dateLabel: "Sat, 7 Mar",
    timeLabel: "9:30 AM – 11:00 AM",
    dateISO: "2026-03-07",
    venue: "Masjid Darul Ghufran, Tampines",
    area: "Tampines",
    capacity: 80,
    taken: 52,
    rsvp: true,
    organiserId: null,
    organiser: "Masjid Darul Ghufran",
    organiserBiz: false,
    blurb:
      "A gentle morning of short surahs and prophetic stories for ages 4–9. Parents welcome to stay.",
    tags: ["Free entry", "Ages 4–9", "Parents welcome"],
    prayerNearby: true,
    halalCatering: false,
    featured: false,
    attendees: 52,
  },
];

events.forEach((e) => {
  e.slug = slugify(e.title);
});

// tickets the demo user already holds
export const myTickets: Ticket[] = [
  { eventId: "e2", tier: "Standard", qty: 1, ref: "HH-TKT-4821", status: "upcoming" },
  { eventId: "e3", tier: "RSVP", qty: 2, ref: "HH-RSVP-1190", status: "upcoming" },
];

export const spotsLeft = (ev: EventItem) => Math.max(0, ev.capacity - ev.taken);
