/* Keep legacy guide URLs trust-safe after the evergreen PDF has been built.
   The source PDF is generated by scripts/build-evergreen-guide.py. */
import { copyFileSync, existsSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const canonical = resolve(root, "public/guides/halal-weekend-planner-singapore.pdf");
const legacy = [
  "ultimate-halal-food-guide-mrt.pdf",
  "halal-brand-cheat-sheet.pdf",
  "ramadan-2026-planner.pdf",
];

if (!existsSync(canonical)) {
  throw new Error("Build scripts/build-evergreen-guide.py first; the canonical planner is missing.");
}

for (const file of legacy) {
  const destination = resolve(root, "public/guides", file);
  copyFileSync(canonical, destination);
  console.log(`Updated safe legacy guide alias: ${file}`);
}
