/* A starter list of popular Muslim baby names with widely-accepted meanings.
   Meanings are commonly-cited renderings, not definitive etymology — parents
   should confirm before naming. Static data, server-filterable for SEO. */

export type Gender = "boy" | "girl";
export interface BabyName { name: string; gender: Gender; meaning: string }

export const BABY_NAMES: BabyName[] = [
  // Boys
  { name: "Adam", gender: "boy", meaning: "The first man; of the earth" },
  { name: "Ahmad", gender: "boy", meaning: "Most praiseworthy, most commendable" },
  { name: "Ali", gender: "boy", meaning: "Exalted, noble, high" },
  { name: "Amir", gender: "boy", meaning: "Prince, leader, commander" },
  { name: "Anas", gender: "boy", meaning: "Affection, friendliness" },
  { name: "Bilal", gender: "boy", meaning: "Water, moisture; name of the Prophet's muezzin" },
  { name: "Dawud", gender: "boy", meaning: "Beloved; the Prophet David" },
  { name: "Faisal", gender: "boy", meaning: "Decisive, a just judge" },
  { name: "Hamza", gender: "boy", meaning: "Lion; strong, steadfast" },
  { name: "Hamid", gender: "boy", meaning: "Praiseworthy, grateful" },
  { name: "Harun", gender: "boy", meaning: "The Prophet Aaron; lofty, exalted" },
  { name: "Hasan", gender: "boy", meaning: "Handsome, good, beautiful" },
  { name: "Husayn", gender: "boy", meaning: "Good, beautiful (diminutive of Hasan)" },
  { name: "Ibrahim", gender: "boy", meaning: "The Prophet Abraham; father of many" },
  { name: "Idris", gender: "boy", meaning: "The Prophet Idris; one who studies" },
  { name: "Imran", gender: "boy", meaning: "Prosperity, long life" },
  { name: "Isa", gender: "boy", meaning: "The Prophet Jesus" },
  { name: "Ismail", gender: "boy", meaning: "The Prophet Ishmael; God will hear" },
  { name: "Kareem", gender: "boy", meaning: "Generous, noble, honourable" },
  { name: "Khalid", gender: "boy", meaning: "Eternal, immortal" },
  { name: "Mahmud", gender: "boy", meaning: "Praised, worthy of praise" },
  { name: "Musa", gender: "boy", meaning: "The Prophet Moses" },
  { name: "Mustafa", gender: "boy", meaning: "The chosen one" },
  { name: "Nasir", gender: "boy", meaning: "Helper, supporter, protector" },
  { name: "Nuh", gender: "boy", meaning: "The Prophet Noah" },
  { name: "Omar", gender: "boy", meaning: "Flourishing, long-lived" },
  { name: "Rashid", gender: "boy", meaning: "Rightly guided, of sound judgement" },
  { name: "Saif", gender: "boy", meaning: "Sword" },
  { name: "Salman", gender: "boy", meaning: "Safe, peaceful, healthy" },
  { name: "Sami", gender: "boy", meaning: "Exalted, sublime; one who listens" },
  { name: "Sulaiman", gender: "boy", meaning: "The Prophet Solomon; peace" },
  { name: "Tariq", gender: "boy", meaning: "Morning star; one who knocks at the door" },
  { name: "Uthman", gender: "boy", meaning: "Wise; companion of the Prophet" },
  { name: "Yahya", gender: "boy", meaning: "The Prophet John; to live" },
  { name: "Yaqub", gender: "boy", meaning: "The Prophet Jacob" },
  { name: "Yasir", gender: "boy", meaning: "Wealthy; one who is at ease" },
  { name: "Yusuf", gender: "boy", meaning: "The Prophet Joseph" },
  { name: "Zaid", gender: "boy", meaning: "Growth, abundance, increase" },
  { name: "Zakariya", gender: "boy", meaning: "The Prophet Zechariah" },
  { name: "Zayn", gender: "boy", meaning: "Beauty, grace, adornment" },

  // Girls
  { name: "Aaliyah", gender: "girl", meaning: "Exalted, sublime, lofty" },
  { name: "Aisha", gender: "girl", meaning: "Living, prosperous; wife of the Prophet" },
  { name: "Amina", gender: "girl", meaning: "Trustworthy, faithful; mother of the Prophet" },
  { name: "Amira", gender: "girl", meaning: "Princess, leader" },
  { name: "Asiya", gender: "girl", meaning: "One who tends and heals; a righteous woman" },
  { name: "Asma", gender: "girl", meaning: "Lofty, eminent; daughter of Abu Bakr" },
  { name: "Bushra", gender: "girl", meaning: "Good news, glad tidings" },
  { name: "Fatima", gender: "girl", meaning: "Captivating; daughter of the Prophet" },
  { name: "Hafsa", gender: "girl", meaning: "Young lioness; wife of the Prophet" },
  { name: "Halima", gender: "girl", meaning: "Gentle, patient, mild-mannered" },
  { name: "Hana", gender: "girl", meaning: "Happiness, bliss, contentment" },
  { name: "Hiba", gender: "girl", meaning: "Gift, present" },
  { name: "Iman", gender: "girl", meaning: "Faith, belief" },
  { name: "Inaya", gender: "girl", meaning: "Care, concern, protection" },
  { name: "Jamila", gender: "girl", meaning: "Beautiful, graceful" },
  { name: "Khadija", gender: "girl", meaning: "Trustworthy; first wife of the Prophet" },
  { name: "Layla", gender: "girl", meaning: "Night; dark beauty" },
  { name: "Lubna", gender: "girl", meaning: "A flowering tree (storax)" },
  { name: "Maha", gender: "girl", meaning: "Gazelle; symbol of beautiful eyes" },
  { name: "Maryam", gender: "girl", meaning: "Mary; mother of the Prophet Jesus" },
  { name: "Maymunah", gender: "girl", meaning: "Blessed, fortunate; wife of the Prophet" },
  { name: "Nadia", gender: "girl", meaning: "Tender, delicate; the caller" },
  { name: "Najwa", gender: "girl", meaning: "Confidential talk, intimate conversation" },
  { name: "Noor", gender: "girl", meaning: "Light, radiance" },
  { name: "Rahma", gender: "girl", meaning: "Mercy, compassion" },
  { name: "Rania", gender: "girl", meaning: "Queenly; one who gazes" },
  { name: "Ruqayya", gender: "girl", meaning: "Rise, ascent; daughter of the Prophet" },
  { name: "Safiyya", gender: "girl", meaning: "Pure, sincere; wife of the Prophet" },
  { name: "Sakina", gender: "girl", meaning: "Tranquillity, calm, serenity" },
  { name: "Salma", gender: "girl", meaning: "Safe, peaceful" },
  { name: "Sana", gender: "girl", meaning: "Radiance, brilliance, splendour" },
  { name: "Sara", gender: "girl", meaning: "Princess; pure" },
  { name: "Sumayya", gender: "girl", meaning: "High, elevated; the first martyr of Islam" },
  { name: "Sundus", gender: "girl", meaning: "Fine silk brocade" },
  { name: "Wafa", gender: "girl", meaning: "Faithfulness, loyalty" },
  { name: "Yasmin", gender: "girl", meaning: "Jasmine flower" },
  { name: "Zahra", gender: "girl", meaning: "Bright, radiant; a flower in bloom" },
  { name: "Zainab", gender: "girl", meaning: "A fragrant flowering plant; daughter of the Prophet" },
  { name: "Zara", gender: "girl", meaning: "Blooming flower; radiance" },
  { name: "Sawda", gender: "girl", meaning: "Wife of the Prophet; one of noble standing" },
];
