/* Al-Asma ul-Husna — the 99 Names of Allah.
   The traditional enumeration (as commonly listed from the narration of
   at-Tirmidhi). Transliterations use a light, readable scheme; meanings are
   given as widely-accepted renderings, not exhaustive theological definitions.
   Static data — rendered server-side for SEO. */

export interface DivineName {
  n: number;
  arabic: string;
  translit: string;
  meaning: string;
}

export const NAMES_OF_ALLAH: DivineName[] = [
  { n: 1, arabic: "الرَّحْمَٰن", translit: "Ar-Rahman", meaning: "The Most Compassionate" },
  { n: 2, arabic: "الرَّحِيم", translit: "Ar-Raheem", meaning: "The Most Merciful" },
  { n: 3, arabic: "الْمَلِك", translit: "Al-Malik", meaning: "The King, The Sovereign" },
  { n: 4, arabic: "الْقُدُّوس", translit: "Al-Quddus", meaning: "The Most Holy" },
  { n: 5, arabic: "السَّلَام", translit: "As-Salam", meaning: "The Source of Peace" },
  { n: 6, arabic: "الْمُؤْمِن", translit: "Al-Mu'min", meaning: "The Granter of Security" },
  { n: 7, arabic: "الْمُهَيْمِن", translit: "Al-Muhaymin", meaning: "The Guardian, The Overseer" },
  { n: 8, arabic: "الْعَزِيز", translit: "Al-'Aziz", meaning: "The Almighty" },
  { n: 9, arabic: "الْجَبَّار", translit: "Al-Jabbar", meaning: "The Compeller, The Restorer" },
  { n: 10, arabic: "الْمُتَكَبِّر", translit: "Al-Mutakabbir", meaning: "The Supreme, The Majestic" },
  { n: 11, arabic: "الْخَالِق", translit: "Al-Khaliq", meaning: "The Creator" },
  { n: 12, arabic: "الْبَارِئ", translit: "Al-Bari'", meaning: "The Originator, The Maker" },
  { n: 13, arabic: "الْمُصَوِّر", translit: "Al-Musawwir", meaning: "The Fashioner of Forms" },
  { n: 14, arabic: "الْغَفَّار", translit: "Al-Ghaffar", meaning: "The Ever-Forgiving" },
  { n: 15, arabic: "الْقَهَّار", translit: "Al-Qahhar", meaning: "The All-Prevailing" },
  { n: 16, arabic: "الْوَهَّاب", translit: "Al-Wahhab", meaning: "The Bestower" },
  { n: 17, arabic: "الرَّزَّاق", translit: "Ar-Razzaq", meaning: "The Provider" },
  { n: 18, arabic: "الْفَتَّاح", translit: "Al-Fattah", meaning: "The Opener, The Judge" },
  { n: 19, arabic: "الْعَلِيم", translit: "Al-'Alim", meaning: "The All-Knowing" },
  { n: 20, arabic: "الْقَابِض", translit: "Al-Qabid", meaning: "The Withholder" },
  { n: 21, arabic: "الْبَاسِط", translit: "Al-Basit", meaning: "The Extender" },
  { n: 22, arabic: "الْخَافِض", translit: "Al-Khafid", meaning: "The Abaser" },
  { n: 23, arabic: "الرَّافِع", translit: "Ar-Rafi'", meaning: "The Exalter" },
  { n: 24, arabic: "الْمُعِزّ", translit: "Al-Mu'izz", meaning: "The Giver of Honour" },
  { n: 25, arabic: "الْمُذِلّ", translit: "Al-Mudhill", meaning: "The Giver of Dishonour" },
  { n: 26, arabic: "السَّمِيع", translit: "As-Sami'", meaning: "The All-Hearing" },
  { n: 27, arabic: "الْبَصِير", translit: "Al-Basir", meaning: "The All-Seeing" },
  { n: 28, arabic: "الْحَكَم", translit: "Al-Hakam", meaning: "The Judge, The Arbitrator" },
  { n: 29, arabic: "الْعَدْل", translit: "Al-'Adl", meaning: "The Utterly Just" },
  { n: 30, arabic: "اللَّطِيف", translit: "Al-Latif", meaning: "The Subtle, The Gentle" },
  { n: 31, arabic: "الْخَبِير", translit: "Al-Khabir", meaning: "The All-Aware" },
  { n: 32, arabic: "الْحَلِيم", translit: "Al-Halim", meaning: "The Forbearing" },
  { n: 33, arabic: "الْعَظِيم", translit: "Al-'Azim", meaning: "The Magnificent" },
  { n: 34, arabic: "الْغَفُور", translit: "Al-Ghafur", meaning: "The All-Forgiving" },
  { n: 35, arabic: "الشَّكُور", translit: "Ash-Shakur", meaning: "The Most Appreciative" },
  { n: 36, arabic: "الْعَلِيّ", translit: "Al-'Ali", meaning: "The Most High" },
  { n: 37, arabic: "الْكَبِير", translit: "Al-Kabir", meaning: "The Most Great" },
  { n: 38, arabic: "الْحَفِيظ", translit: "Al-Hafiz", meaning: "The Preserver" },
  { n: 39, arabic: "الْمُقِيت", translit: "Al-Muqit", meaning: "The Sustainer, The Nourisher" },
  { n: 40, arabic: "الْحَسِيب", translit: "Al-Hasib", meaning: "The Reckoner" },
  { n: 41, arabic: "الْجَلِيل", translit: "Al-Jalil", meaning: "The Majestic" },
  { n: 42, arabic: "الْكَرِيم", translit: "Al-Karim", meaning: "The Most Generous" },
  { n: 43, arabic: "الرَّقِيب", translit: "Ar-Raqib", meaning: "The Watchful" },
  { n: 44, arabic: "الْمُجِيب", translit: "Al-Mujib", meaning: "The Responsive, The Answerer" },
  { n: 45, arabic: "الْوَاسِع", translit: "Al-Wasi'", meaning: "The All-Encompassing, The Vast" },
  { n: 46, arabic: "الْحَكِيم", translit: "Al-Hakim", meaning: "The All-Wise" },
  { n: 47, arabic: "الْوَدُود", translit: "Al-Wadud", meaning: "The Most Loving" },
  { n: 48, arabic: "الْمَجِيد", translit: "Al-Majid", meaning: "The Most Glorious" },
  { n: 49, arabic: "الْبَاعِث", translit: "Al-Ba'ith", meaning: "The Resurrector" },
  { n: 50, arabic: "الشَّهِيد", translit: "Ash-Shahid", meaning: "The Witness" },
  { n: 51, arabic: "الْحَقّ", translit: "Al-Haqq", meaning: "The Truth, The Reality" },
  { n: 52, arabic: "الْوَكِيل", translit: "Al-Wakil", meaning: "The Trustee, The Disposer of Affairs" },
  { n: 53, arabic: "الْقَوِيّ", translit: "Al-Qawiyy", meaning: "The All-Strong" },
  { n: 54, arabic: "الْمَتِين", translit: "Al-Matin", meaning: "The Firm, The Steadfast" },
  { n: 55, arabic: "الْوَلِيّ", translit: "Al-Waliyy", meaning: "The Protecting Friend, The Patron" },
  { n: 56, arabic: "الْحَمِيد", translit: "Al-Hamid", meaning: "The Praiseworthy" },
  { n: 57, arabic: "الْمُحْصِي", translit: "Al-Muhsi", meaning: "The Enumerator" },
  { n: 58, arabic: "الْمُبْدِئ", translit: "Al-Mubdi'", meaning: "The Originator, The Initiator" },
  { n: 59, arabic: "الْمُعِيد", translit: "Al-Mu'id", meaning: "The Restorer, The Reinstater" },
  { n: 60, arabic: "الْمُحْيِي", translit: "Al-Muhyi", meaning: "The Giver of Life" },
  { n: 61, arabic: "الْمُمِيت", translit: "Al-Mumit", meaning: "The Causer of Death" },
  { n: 62, arabic: "الْحَيّ", translit: "Al-Hayy", meaning: "The Ever-Living" },
  { n: 63, arabic: "الْقَيُّوم", translit: "Al-Qayyum", meaning: "The Sustainer of All" },
  { n: 64, arabic: "الْوَاجِد", translit: "Al-Wajid", meaning: "The Perceiver, The Finder" },
  { n: 65, arabic: "الْمَاجِد", translit: "Al-Majid", meaning: "The Illustrious, The Noble" },
  { n: 66, arabic: "الْوَاحِد", translit: "Al-Wahid", meaning: "The One" },
  { n: 67, arabic: "الْأَحَد", translit: "Al-Ahad", meaning: "The Unique, The Indivisible" },
  { n: 68, arabic: "الصَّمَد", translit: "As-Samad", meaning: "The Eternal, The Self-Sufficient" },
  { n: 69, arabic: "الْقَادِر", translit: "Al-Qadir", meaning: "The All-Capable" },
  { n: 70, arabic: "الْمُقْتَدِر", translit: "Al-Muqtadir", meaning: "The Omnipotent" },
  { n: 71, arabic: "الْمُقَدِّم", translit: "Al-Muqaddim", meaning: "The Expediter" },
  { n: 72, arabic: "الْمُؤَخِّر", translit: "Al-Mu'akhkhir", meaning: "The Delayer" },
  { n: 73, arabic: "الْأَوَّل", translit: "Al-Awwal", meaning: "The First" },
  { n: 74, arabic: "الْآخِر", translit: "Al-Akhir", meaning: "The Last" },
  { n: 75, arabic: "الظَّاهِر", translit: "Az-Zahir", meaning: "The Manifest" },
  { n: 76, arabic: "الْبَاطِن", translit: "Al-Batin", meaning: "The Hidden, The Inmost" },
  { n: 77, arabic: "الْوَالِي", translit: "Al-Wali", meaning: "The Governor, The Patron" },
  { n: 78, arabic: "الْمُتَعَالِي", translit: "Al-Muta'ali", meaning: "The Most Exalted" },
  { n: 79, arabic: "الْبَرّ", translit: "Al-Barr", meaning: "The Source of Goodness" },
  { n: 80, arabic: "التَّوَّاب", translit: "At-Tawwab", meaning: "The Acceptor of Repentance" },
  { n: 81, arabic: "الْمُنْتَقِم", translit: "Al-Muntaqim", meaning: "The Avenger" },
  { n: 82, arabic: "الْعَفُوّ", translit: "Al-'Afuww", meaning: "The Pardoner" },
  { n: 83, arabic: "الرَّؤُوف", translit: "Ar-Ra'uf", meaning: "The Most Kind" },
  { n: 84, arabic: "مَالِكُ الْمُلْك", translit: "Malik-ul-Mulk", meaning: "Master of the Kingdom" },
  { n: 85, arabic: "ذُو الْجَلَالِ وَالْإِكْرَام", translit: "Dhul-Jalali wal-Ikram", meaning: "Lord of Majesty and Generosity" },
  { n: 86, arabic: "الْمُقْسِط", translit: "Al-Muqsit", meaning: "The Equitable" },
  { n: 87, arabic: "الْجَامِع", translit: "Al-Jami'", meaning: "The Gatherer" },
  { n: 88, arabic: "الْغَنِيّ", translit: "Al-Ghani", meaning: "The Self-Sufficient" },
  { n: 89, arabic: "الْمُغْنِي", translit: "Al-Mughni", meaning: "The Enricher" },
  { n: 90, arabic: "الْمَانِع", translit: "Al-Mani'", meaning: "The Preventer, The Withholder" },
  { n: 91, arabic: "الضَّارّ", translit: "Ad-Darr", meaning: "The Creator of Harm" },
  { n: 92, arabic: "النَّافِع", translit: "An-Nafi'", meaning: "The Bestower of Benefit" },
  { n: 93, arabic: "النُّور", translit: "An-Nur", meaning: "The Light" },
  { n: 94, arabic: "الْهَادِي", translit: "Al-Hadi", meaning: "The Guide" },
  { n: 95, arabic: "الْبَدِيع", translit: "Al-Badi'", meaning: "The Incomparable Originator" },
  { n: 96, arabic: "الْبَاقِي", translit: "Al-Baqi", meaning: "The Everlasting" },
  { n: 97, arabic: "الْوَارِث", translit: "Al-Warith", meaning: "The Inheritor, The Heir" },
  { n: 98, arabic: "الرَّشِيد", translit: "Ar-Rashid", meaning: "The Guide to the Right Path" },
  { n: 99, arabic: "الصَّبُور", translit: "As-Sabur", meaning: "The Most Patient" },
];
