/* The 114 surahs of the Qur'an (number, transliterated name, English name).
   Canonical order. Used by the Hifz tracker and reusable for a future Quran
   reader. Static data. */

export interface Surah {
  n: number;
  name: string; // transliteration
  english: string;
}

export const SURAHS: Surah[] = [
  { n: 1, name: "Al-Fatihah", english: "The Opening" },
  { n: 2, name: "Al-Baqarah", english: "The Cow" },
  { n: 3, name: "Ali 'Imran", english: "Family of Imran" },
  { n: 4, name: "An-Nisa", english: "The Women" },
  { n: 5, name: "Al-Ma'idah", english: "The Table Spread" },
  { n: 6, name: "Al-An'am", english: "The Cattle" },
  { n: 7, name: "Al-A'raf", english: "The Heights" },
  { n: 8, name: "Al-Anfal", english: "The Spoils of War" },
  { n: 9, name: "At-Tawbah", english: "The Repentance" },
  { n: 10, name: "Yunus", english: "Jonah" },
  { n: 11, name: "Hud", english: "Hud" },
  { n: 12, name: "Yusuf", english: "Joseph" },
  { n: 13, name: "Ar-Ra'd", english: "The Thunder" },
  { n: 14, name: "Ibrahim", english: "Abraham" },
  { n: 15, name: "Al-Hijr", english: "The Rocky Tract" },
  { n: 16, name: "An-Nahl", english: "The Bee" },
  { n: 17, name: "Al-Isra", english: "The Night Journey" },
  { n: 18, name: "Al-Kahf", english: "The Cave" },
  { n: 19, name: "Maryam", english: "Mary" },
  { n: 20, name: "Ta-Ha", english: "Ta-Ha" },
  { n: 21, name: "Al-Anbiya", english: "The Prophets" },
  { n: 22, name: "Al-Hajj", english: "The Pilgrimage" },
  { n: 23, name: "Al-Mu'minun", english: "The Believers" },
  { n: 24, name: "An-Nur", english: "The Light" },
  { n: 25, name: "Al-Furqan", english: "The Criterion" },
  { n: 26, name: "Ash-Shu'ara", english: "The Poets" },
  { n: 27, name: "An-Naml", english: "The Ant" },
  { n: 28, name: "Al-Qasas", english: "The Stories" },
  { n: 29, name: "Al-'Ankabut", english: "The Spider" },
  { n: 30, name: "Ar-Rum", english: "The Romans" },
  { n: 31, name: "Luqman", english: "Luqman" },
  { n: 32, name: "As-Sajdah", english: "The Prostration" },
  { n: 33, name: "Al-Ahzab", english: "The Combined Forces" },
  { n: 34, name: "Saba", english: "Sheba" },
  { n: 35, name: "Fatir", english: "Originator" },
  { n: 36, name: "Ya-Sin", english: "Ya-Sin" },
  { n: 37, name: "As-Saffat", english: "Those Who Set the Ranks" },
  { n: 38, name: "Sad", english: "Sad" },
  { n: 39, name: "Az-Zumar", english: "The Troops" },
  { n: 40, name: "Ghafir", english: "The Forgiver" },
  { n: 41, name: "Fussilat", english: "Explained in Detail" },
  { n: 42, name: "Ash-Shura", english: "The Consultation" },
  { n: 43, name: "Az-Zukhruf", english: "The Ornaments of Gold" },
  { n: 44, name: "Ad-Dukhan", english: "The Smoke" },
  { n: 45, name: "Al-Jathiyah", english: "The Crouching" },
  { n: 46, name: "Al-Ahqaf", english: "The Wind-Curved Sandhills" },
  { n: 47, name: "Muhammad", english: "Muhammad" },
  { n: 48, name: "Al-Fath", english: "The Victory" },
  { n: 49, name: "Al-Hujurat", english: "The Rooms" },
  { n: 50, name: "Qaf", english: "Qaf" },
  { n: 51, name: "Adh-Dhariyat", english: "The Winnowing Winds" },
  { n: 52, name: "At-Tur", english: "The Mount" },
  { n: 53, name: "An-Najm", english: "The Star" },
  { n: 54, name: "Al-Qamar", english: "The Moon" },
  { n: 55, name: "Ar-Rahman", english: "The Beneficent" },
  { n: 56, name: "Al-Waqi'ah", english: "The Inevitable" },
  { n: 57, name: "Al-Hadid", english: "The Iron" },
  { n: 58, name: "Al-Mujadila", english: "The Pleading Woman" },
  { n: 59, name: "Al-Hashr", english: "The Exile" },
  { n: 60, name: "Al-Mumtahanah", english: "She That Is to Be Examined" },
  { n: 61, name: "As-Saff", english: "The Ranks" },
  { n: 62, name: "Al-Jumu'ah", english: "Friday" },
  { n: 63, name: "Al-Munafiqun", english: "The Hypocrites" },
  { n: 64, name: "At-Taghabun", english: "The Mutual Disillusion" },
  { n: 65, name: "At-Talaq", english: "The Divorce" },
  { n: 66, name: "At-Tahrim", english: "The Prohibition" },
  { n: 67, name: "Al-Mulk", english: "The Sovereignty" },
  { n: 68, name: "Al-Qalam", english: "The Pen" },
  { n: 69, name: "Al-Haqqah", english: "The Reality" },
  { n: 70, name: "Al-Ma'arij", english: "The Ascending Stairways" },
  { n: 71, name: "Nuh", english: "Noah" },
  { n: 72, name: "Al-Jinn", english: "The Jinn" },
  { n: 73, name: "Al-Muzzammil", english: "The Enshrouded One" },
  { n: 74, name: "Al-Muddaththir", english: "The Cloaked One" },
  { n: 75, name: "Al-Qiyamah", english: "The Resurrection" },
  { n: 76, name: "Al-Insan", english: "Man" },
  { n: 77, name: "Al-Mursalat", english: "The Emissaries" },
  { n: 78, name: "An-Naba", english: "The Tidings" },
  { n: 79, name: "An-Nazi'at", english: "Those Who Drag Forth" },
  { n: 80, name: "'Abasa", english: "He Frowned" },
  { n: 81, name: "At-Takwir", english: "The Overthrowing" },
  { n: 82, name: "Al-Infitar", english: "The Cleaving" },
  { n: 83, name: "Al-Mutaffifin", english: "The Defrauding" },
  { n: 84, name: "Al-Inshiqaq", english: "The Sundering" },
  { n: 85, name: "Al-Buruj", english: "The Mansions of the Stars" },
  { n: 86, name: "At-Tariq", english: "The Morning Star" },
  { n: 87, name: "Al-A'la", english: "The Most High" },
  { n: 88, name: "Al-Ghashiyah", english: "The Overwhelming" },
  { n: 89, name: "Al-Fajr", english: "The Dawn" },
  { n: 90, name: "Al-Balad", english: "The City" },
  { n: 91, name: "Ash-Shams", english: "The Sun" },
  { n: 92, name: "Al-Layl", english: "The Night" },
  { n: 93, name: "Ad-Duha", english: "The Morning Hours" },
  { n: 94, name: "Ash-Sharh", english: "The Relief" },
  { n: 95, name: "At-Tin", english: "The Fig" },
  { n: 96, name: "Al-'Alaq", english: "The Clot" },
  { n: 97, name: "Al-Qadr", english: "The Power" },
  { n: 98, name: "Al-Bayyinah", english: "The Clear Proof" },
  { n: 99, name: "Az-Zalzalah", english: "The Earthquake" },
  { n: 100, name: "Al-'Adiyat", english: "The Courser" },
  { n: 101, name: "Al-Qari'ah", english: "The Calamity" },
  { n: 102, name: "At-Takathur", english: "The Rivalry in World Increase" },
  { n: 103, name: "Al-'Asr", english: "The Declining Day" },
  { n: 104, name: "Al-Humazah", english: "The Traducer" },
  { n: 105, name: "Al-Fil", english: "The Elephant" },
  { n: 106, name: "Quraysh", english: "Quraysh" },
  { n: 107, name: "Al-Ma'un", english: "The Small Kindnesses" },
  { n: 108, name: "Al-Kawthar", english: "The Abundance" },
  { n: 109, name: "Al-Kafirun", english: "The Disbelievers" },
  { n: 110, name: "An-Nasr", english: "The Divine Support" },
  { n: 111, name: "Al-Masad", english: "The Palm Fiber" },
  { n: 112, name: "Al-Ikhlas", english: "The Sincerity" },
  { n: 113, name: "Al-Falaq", english: "The Daybreak" },
  { n: 114, name: "An-Nas", english: "Mankind" },
];
